export const FETCH_WEATHER_REQUEST: string = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS: string = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FALIURE: string = 'FETCH_WEATHER_FALIURE';

export const FETCH_FORECAST_REQUEST: string = 'FETCH_FORECAST_REQUEST';
export const FETCH_FORECAST_SUCCESS: string = 'FETCH_FORECAST_SUCCESS';
export const FETCH_FORECAST_FALIURE: string = 'FETCH_FORECAST_FALIURE';